- name: 'Catalina Cáceres'
  pic: 'CCaceres.JPG'

- name: 'Cristian Cisternas'
  pic: 'Cisternas.JPG'

- name: 'Fernando Fetis'
  pic: 'FFetis.jpg'

- name: 'Nicolás Fredes'
  pic: 'NFredes.JPG'

- name: 'Diego González'
  pic: 'DGonzalez.JPG'

- name: 'Enzo Iubini'
  pic: 'Iubini.JPG'

- name: 'Nicole Jara'
  pic: 'NJara.JPG'

- name: 'Nicolás Jiménez'
  pic: 'NJimenez.JPG'

- name: 'Alejandro Luzanto'
  pic: 'Luzanto.JPG'

- name: 'Samuel Madera'
  pic: 'Sam.JPG'

- name: 'Fernando Maron'
  pic: 'Maron.JPG'

- name: 'Antonio Montalva'
  pic: 'Montalva.JPG'

- name: 'Javier Mosnaim'
  pic: 'Mosnaim.JPG'

- name: 'Diego Ortego'
  pic: 'DOrtego.JPG'

- name: 'Cristóbal Peralta'
  pic: 'Peralta.JPG'

- name: 'Diego Rivera'
  pic: 'DRivera.JPG'

- name: 'Pavan Samtani'
  pic: 'PSamtani.JPG'

- name: 'Julián Solís'
  pic: 'Julian.JPG'

- name: 'Juan Urrutia'
  pic: 'JUrrutia.JPG'

- name: 'Kelly Wagermann'
  pic: 'Kelly.JPG'